### ISSUE TITLE
GSHHG version

### ISSUE THREAD

**Issue by atakGitHub** [jmlondon/ptolemy#1]
Hi, Thank you very much for this new tool. A colleague recommended this NPacMaps to me, and it looks very nice. I just had a trouble downloading GSHHG data, because GSHHG is updated to 2.3.7 from 2.3.6. How can I specify 2.3.7 during install_gshhg() ? Many thanks, Akinori

**Comment by jmlondon** [comment]
sorry for the delay on addressing this. I've updated the code to now use 2.3.7 (#2 )

**Comment by atakGitHub** [comment]
Thank you very much for your help!

**Comment by jmlondon** [comment]
I should have closed this a while ago, but forgot. Doing so now and also using this an opportunity to bring your attention to the name change and rewrite. Please file any issues if you have problems.
