### ISSUE TITLE
Bug in extract_gshhg.R

### ISSUE THREAD

**Issue by rmendels** [jmlondon/ptolemy#11]
I get an error when the package tries to load the data.  I believe it is from these lines in `extract_gshhg.R()` - lines 30-32

```r
  dir_path <- system.file("extData", package = "nPacMaps")
  file_name <- paste0("gshhs_",resolution,".b")
  gshhg_path <- paste(dir_path, "gshhg-bin-2.3.7", file_name, sep = "/")
```

That is the old package name,  and fails now in setting up the path to the directory.

**Comment by jmlondon** [comment]
fixed, I hope, in #12.
